### ISSUE TITLE
Not working on v0.7.1?

### ISSUE THREAD

**Issue by SOLiNARY** [ruipin/fvtt-token-vision-tweaks#2]
Seems like it is not working for new version.
![image](https://user-images.githubusercontent.com/3579801/90377893-baf54900-e089-11ea-8d4d-83c547616cbb.png)
![image](https://user-images.githubusercontent.com/3579801/90377938-cb0d2880-e089-11ea-9c84-9136c1d28d1f.png)

**Comment by ruipin** [comment]
Not surprising, since 0.7.1 rewrote a massive portion of the lighting system. This plugin would probably need a significant rewrite to make compatible with it - there is a reason it only lists 0.6.5 as compatible (although it should work in 0.7.0 as this part of the code wasn't touched).

I won't be updating this plugin to work on Alpha releases of Foundry VTT, considering how likely it is for the lighting system to change again before the final release, causing wasted work from my end. I also don't use Alpha releases, so it would be a maintenance headache - especially if I had to try to keep compatibility with 0.6.5.

Fortunately, the two bugs ("Aggressive Wall Culling" and "Fog-of-War Memory Leak") should now be fixed in 0.7.1, so the module isn't as important as it was for 0.6.5/0.7.0.

**Comment by ruipin** [comment]
This module has now supported FVTT 0.7.x since [v1.3.0](https://github.com/ruipin/fvtt-token-vision-tweaks/releases/tag/v1.3.0).

Closing.
